name: 'Hello CodeThreat'
description: 'Greet someone and record the time'
inputs:
  ACCESS_TOKEN:  # id of input
    description: 'ACCESSTOKEN'
    required: true
    default: ''
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'
